Modal
js-tasks-ru/htmlcss-20220414_demeshko-egor pull request #16
Opened 2022-05-08 15:16 UTC by Egor-Demeshko

реализация модалки

2022-05-08 15:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-10 19:41 UTC, GSemikozov requested changes

2022-05-10 19:41 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +          <button type="button" name="button" class="button  button_primary"
эта кнопка - не часть компонента Модалка

2022-05-10 19:41 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +          <section class="modal__pop-up" id="modal">
это должен быть .modal

2022-05-10 19:41 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__pop-up{
это .modal, а то что выше - лишнее

2022-05-10 19:41 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
обязательно fixed

2022-05-10 19:41 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__message-box{
.modal__window

2022-05-10 19:41 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: 15.33px;
дробные пиксели не стоит использовать

2022-05-11 07:47 UTC, Egor-Demeshko commented on 05-lection3/02-modal/index.html
> +          <button type="button" name="button" class="button  button_primary"
да. мог догадаться я

2022-05-11 07:55 UTC, Egor-Demeshko commented on 05-lection3/02-modal/modal.css
> +.modal__pop-up{
да. я не дочитал до этого, но когда button вынес из модалки сразу стало понятно что это лишнее))

2022-05-11 07:55 UTC, Egor-Demeshko commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
ой. не поправил. секундочку.

2022-05-11 18:56 UTC, GSemikozov approved these changes

2022-05-11 18:56 UTC, merged