Avatar
js-tasks-ru/htmlcss-20220414_demeshko-egor pull request #18
Opened 2022-05-09 13:06 UTC by Egor-Demeshko

почему-то не работает тег picture. перечитал, перекрутил, так и не понял в чем дело. причем у меня не хочет webp грузится картинка из кода. в отдельном окне браузер ее открывает.

2022-05-09 13:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-09 13:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-10 19:50 UTC, GSemikozov requested changes

2022-05-10 19:50 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +            <source srcset="./public/avatar-200.jpg" type="image/jpeg">
тип указывать не обязательно

2022-05-10 19:50 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +            <img src="./public/avatar-200.jpg" alt="user\'s avatar" class="avatar__img">
класс можно задать на picture. Но вообще, конкретно в данном случае нет абсолютно никакой необходимости использовать этот тег - пользователь не будет загружать свою аватарку в разных форматах и разрешениях))

2022-05-10 19:50 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  object-fit: cover;
это свойство должно быть указано у .avatar__img (+ ширина и высота 100%)

2022-05-10 19:50 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar{
у данного блока должны быть зафиксированы размеры - 102х102

2022-05-11 13:31 UTC, Egor-Demeshko commented on 06-lection4/01-avatar/index.html
> +            <img src="./public/avatar-200.jpg" alt="user\'s avatar" class="avatar__img">
хотелось потренироваться(

2022-05-11 13:39 UTC, Egor-Demeshko commented on 06-lection4/01-avatar/avatar.css
> +.avatar{
а обычно в стайл гайдах или ТЗ указывают как-то, какие элементы должны быть гибкие, а какие с фикс размером?
или общепризнано что автарка имеет жесткий фикс?

2022-05-11 19:00 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar{
зависит от контекста, чаще смотрим на макеты в разных разрешениях и понимает как правильно реализовать + всегда можно посоветоваться с дизайнером

2022-05-11 19:01 UTC, GSemikozov approved these changes

2022-05-11 19:01 UTC, merged