Background image
js-tasks-ru/htmlcss-20220414_demeshko-egor pull request #19
Opened 2022-05-09 13:27 UTC by Egor-Demeshko

реализовал через max-width и каскад

2022-05-09 13:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-10 19:51 UTC, GSemikozov requested changes

2022-05-10 19:51 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media(max-width: 2560px){
лишний медиа запрос, данный фон должен быть указан сразу на body

2022-05-11 19:01 UTC, GSemikozov approved these changes

2022-05-11 19:01 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-05-11 19:02 UTC, GSemikozov approved these changes

2022-05-11 19:02 UTC, merged