реализация radio
js-tasks-ru/htmlcss-20220414_demeshko-egor pull request #25
Opened 2022-05-15 20:30 UTC by Egor-Demeshko

реализовал надпись через псевдокласс after.
я хотел сделать динамическую замену надписи, в зависимости от состояния radio.
не уверен что я правильно уловил как это делается. 
выглядит немного резкова-то. 
из проблем на мой взгляди фиксировая ширина.

2022-05-15 20:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-16 09:27 UTC, GSemikozov requested changes

2022-05-16 09:27 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  width: 102px;
ширину не нужно фиксировать, тайтл может быть разной длины, а может и вообще отсутствовать

2022-05-16 09:27 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  margin: 1px;
а зачем?) удалим

2022-05-16 09:27 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio__visual::after{
здесь можно без absolute обойтись

2022-05-16 09:27 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  margin: 0;
удалим

2022-05-16 14:47 UTC, Egor-Demeshko commented on 07-lection5/02-radio/radio.css
> +  margin: 1px;
Потому что тогда верстка двигается, в такое реализации, из-за того что ширина границы у нас разная

2022-05-16 18:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-16 18:45 UTC, Egor-Demeshko commented on 07-lection5/02-radio/radio.css
> +  margin: 1px;
я вообщем-то перемолол в голове кое-какую информацию, поэтому проект изменился. НО непотопляемый марджин остался, только он теперь другой, но его изменение, как и в ранней версии отвечает за компенсацию роста границы radio__visual, при radio checked

2022-05-16 18:47 UTC, Egor-Demeshko commented on 07-lection5/02-radio/radio.css
> +  margin: 1px;
gap родительского блока удален, так как к нему не могу получить доступ при input radio checked.

2022-05-16 18:48 UTC, Egor-Demeshko commented on 07-lection5/02-radio/radio.css
> +  margin: 0;
не удаляется(((

2022-05-16 19:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-17 13:52 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  margin: 1px;
если причина - добавление / сокрытие бордера, то это решается обычным box-sizing: border-box

2022-05-17 13:53 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  margin: 0;
чуть выше написал, почему можно все-таки удалить)

2022-05-17 13:54 UTC, GSemikozov requested changes

2022-05-17 13:54 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  margin-right: 11px;
лишнее, если ориентироваться на коммент по поводу марджинов

2022-05-19 16:39 UTC, Egor-Demeshko commented on 07-lection5/02-radio/radio.css
> +  margin: 1px;
туговат я)

2022-05-20 17:54 UTC, GSemikozov approved these changes

2022-05-20 17:54 UTC, merged