Toggler
js-tasks-ru/htmlcss-20220414_demeshko-egor pull request #26
Opened 2022-05-17 17:47 UTC by Egor-Demeshko

реализация toggler
в отступление от тз при фокус опять добавлена тень.
подчеркивание текста сохраняется и при состоянии :active

2022-05-17 17:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-17 19:12 UTC, GSemikozov requested changes

2022-05-17 19:12 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  height: 23px;
вроде как 24 )

2022-05-19 17:19 UTC, Egor-Demeshko commented on 07-lection5/03-toggler/toggler.css
> +  height: 23px;
мне не понравилось как выглядит с 24px))я знаю что от ТЗ отступать нельзя или по согласованию. сча посмотрим что надо поправить

2022-05-19 17:29 UTC, Egor-Demeshko commented on 07-lection5/03-toggler/toggler.css
> +  height: 23px;
главное, в этом элементе бодербокс сделал)

2022-05-20 17:53 UTC, GSemikozov approved these changes

2022-05-20 17:53 UTC, merged