полное решение ДЗ по лекции 1
js-tasks-ru/htmlcss-20220414_demeshko-egor pull request #3
Opened 2022-04-24 17:07 UTC by Egor-Demeshko

2022-04-24 17:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-24 18:24 UTC, GSemikozov requested changes

2022-04-24 18:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +body{
глобальные стили в файле стилей конкретного блока ни в коем случае не добавляем. И это лишь для того чтобы формально добавить на странице примере верстки отступы? такие стили можно добавлять прямо на хтмл страницу в теге style

2022-04-24 18:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width:189px;
ширину лучше жестко не фиксировать, пусть растягивается по внутреннему содержимому

2022-04-24 18:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button:disabled:hover{
у disabled не должно быть ховеров и прочих состояний - чтобы пользователь никак не мог взаимодействовать с таким элементом можно добавить pointer-events: none

2022-04-24 18:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  color: white;
для белого цвета есть перменная

2022-04-24 18:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  background-color: #2342C0;
если переменных для конкретных цветов еще нет - надо создать )

2022-04-24 18:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled{
disabled уже задан на .button, не нужно дополнительно дублировать на каждом типе кнопки

2022-04-24 19:35 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +body{
просто на странице добавить отступы для красоты. 
в дз писали вроде что блоки не будут эти использоваться, так я себе позволил исключение)

2022-04-24 19:49 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +  width:189px;
подумал, надо делать жестко как по тз)

2022-04-24 19:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-25 07:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +body{
да, но такие стили добавляются точно не в файле стилей компонента, который как раз таки будет переиспользоваться)

2022-04-25 07:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width:189px;
в дизайне верстка такая: есть сетка с ячейками, в которые встраиваются кнопки, кнопки при этом растягиваются по ширине ячеек, поэтому у всех и одинаковая ширина. Задается это или через класс-микс, или через модификатор (например, .button_block / .button_full_width). Но так делать в данном случае не нужно, мы делаем решение только для компонента Кнопка, а не для компонента таблицы кнопок.)

2022-04-25 07:10 UTC, GSemikozov requested changes

2022-04-25 07:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  border 200ms ease-in-out, color 200ms ease-in-out;
пропущено `:`

2022-04-26 18:07 UTC, closed without merging

2022-04-26 18:07 UTC, Egor-Demeshko commented
не правильно