Burger
js-tasks-ru/htmlcss-20220414_demeshko-egor pull request #31
Opened 2022-05-28 17:18 UTC by Egor-Demeshko

черновая реализация бургер

2022-05-28 17:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-29 04:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-29 04:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-29 20:56 UTC, GSemikozov requested changes

2022-05-29 20:56 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__menu{
это и есть блок .burger

2022-05-29 20:56 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__menu-button{
кнопка вызова - это не часть блока бургер-меню, нужно немного скорректировать верстку

2022-05-31 10:12 UTC, GSemikozov approved these changes

2022-05-31 10:12 UTC, merged