решение задачи про кнопки
js-tasks-ru/htmlcss-20220414_demeshko-egor pull request #6
Opened 2022-04-27 19:43 UTC by Egor-Demeshko

2022-04-27 19:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 19:47 UTC, GSemikozov requested changes

2022-04-27 19:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +body{
на уровне компонента такие вспомогательные стили не указываем - здесь могут быть только стили самого блока + его элементы и модификаторы

2022-04-27 19:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width:189px;
ширину не стоит фиксировать (текста может быть больше)

2022-04-27 19:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +   cursor: not-allowed;
лучше pointer-events: none

2022-04-27 19:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button:disabled:hover{
чтобы у disabled не было ховеров и пр.

2022-04-27 19:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  color: white;
`var(--white)`

2022-04-27 19:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled{
уже есть .button:disabled, не нужно дублировать на каждый тип кнопки

2022-04-27 19:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled{
и ниже то же самое

2022-04-27 19:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  background-color: white;
`var(--white)`

2022-04-27 19:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  background-color: white;
везде перепроверить и проставить цвета из переменных

2022-04-27 20:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 20:16 UTC, GSemikozov requested changes

2022-04-27 20:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding:15px 66px;
`15px 15px 14px`

2022-04-27 20:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  border 200ms ease-in-out, color 200ms ease-in-out;
`:`

2022-04-27 20:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +   background-color: var(--blue);
удалим)

2022-04-27 20:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +   color: var(--white);
и тут

2022-04-27 20:24 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +body{
сделал инлайном в разметке.

2022-04-27 20:25 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +  width:189px;
переделал через падинги блока.

2022-04-27 20:25 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +   cursor: not-allowed;
применил ваше решение.

2022-04-27 20:26 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +.button:disabled:hover{
убрал полность это ccs правило

2022-04-27 20:26 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +  color: white;
сделал через переменную

2022-04-27 20:26 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +.button_primary:disabled{
убрал эти правила

2022-04-27 20:26 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +  background-color: white;
сделал через переменную

2022-04-27 20:27 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +  background-color: white;
done

2022-04-27 20:28 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +  padding:15px 66px;
done

2022-04-27 20:29 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +  border 200ms ease-in-out, color 200ms ease-in-out;
если речь про border, то это продолжения правила transition;

2022-04-27 20:31 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +   background-color: var(--blue);
ok

2022-04-27 20:31 UTC, Egor-Demeshko commented on 03-lection1/01-button/button.css
> +   color: var(--white);
ok

2022-04-27 20:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-28 16:05 UTC, GSemikozov approved these changes

2022-04-28 16:05 UTC, merged