верстка страницы без синих карточек
js-tasks-ru/htmlcss-20220414_demeshko-egor pull request #8
Opened 2022-05-01 16:40 UTC by Egor-Demeshko

реализации верстки страницы, без синих карточек пока. 3 карточки хотел добавить после этого одобрения.

2022-05-01 16:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-02 08:06 UTC, GSemikozov requested changes

2022-05-02 08:06 UTC, GSemikozov commented on components/footer/footer.css
> +  max-width: 1440px;
по дизайну просто растягивается на всю ширину вьюпорта

2022-05-02 08:06 UTC, GSemikozov commented on components/footer/footer.css
> +  max-width: 111px;
лишнее

2022-05-02 08:06 UTC, GSemikozov commented on components/footer/footer.css
> +  margin-bottom: 0;
сверху уже марджин есть)

2022-05-02 08:06 UTC, GSemikozov commented on components/page/page.css
> +  max-width: 1440px;
то же самое что и с футером

2022-05-02 08:06 UTC, GSemikozov commented on components/page/page.css
> +  margin: 0 auto;
и тогда это лишнее

2022-05-02 08:06 UTC, GSemikozov commented on components/preview/preview.css
> +  max-width: 1440px;
и тут удалить

2022-05-02 08:06 UTC, GSemikozov commented on components/container/container.css
> +  max-width: 1040px;
1110px

2022-05-02 09:18 UTC, Egor-Demeshko commented on components/footer/footer.css
> +  max-width: 1440px;
ну в фигме написали 1440)

2022-05-02 09:36 UTC, GSemikozov commented on components/footer/footer.css
> +  max-width: 1440px;
в фигме мы не можем учитывать абсолютно все размеры мониторов) поэтому для примера десктоп обычно делают макет на холсте 1440

2022-05-02 09:38 UTC, GSemikozov approved these changes

2022-05-02 09:38 UTC, merged